force-app/main/default/objects/JobPosition__c/JobPosition__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobPosition__c/fields/HR_Manager__c.field-meta.xml
<CustomField>
    <fullName>HR_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>HR Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobPosition__c/fields/Position_Budget__c.field-meta.xml
<CustomField>
    <fullName>Position_Budget__c</fullName>
    <label>Position Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobPosition__c/fields/Practice_Unit__c.field-meta.xml
<CustomField>
    <fullName>Practice_Unit__c</fullName>
    <label>Practice Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/triggers/JobPosition/JobPositionTriggerHelper.cls
public with sharing class JobPositionTriggerHelper {
    public static void updateJobPositionsTitle(List<JobPosition__c> JobPositions){
        for( JobPosition__c  positionitem: JobPositions)
        {
            if(positionitem.Practice_Unit__c == 'Salesforce')
            {
                positionitem.Name= 'SF-'+positionitem.Name;
            }
        }
    }
    
    public static void createTaskforHR(Map<Id,JobPosition__c> OldJobPositions,Map<Id,JobPosition__c> NewJobPositions){
        List<Task> taskList = new List<Task>();
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        Map<Id,Contact> contacts = new Map<Id,Contact>([Select Id, Email from Contact]);
        
        for( JobPosition__c newPosition: NewJobPositions.values())
        {
            JobPosition__c oldPosition = OldJobPositions.get(newPosition.Id);
            Contact hr= contacts.get(oldPosition.HR_Manager__c);
            
            if((newPosition.Position_Budget__c != oldPosition.Position_Budget__c) && newPosition.Position_Budget__c>5000){
                Task newTask = new Task(OwnerId = UserInfo.getUserId(), Subject='Review high budget position '+ oldPosition.Name, Status='New',WhoId=hr.Id );
                taskList.add(newTask);
                
                Messaging.SingleEmailMessage CaseNotificationmail = new Messaging.SingleEmailMessage();
                CaseNotificationmail.setToAddresses(new List<String> { hr.Email });
                CaseNotificationmail.setReplyTo('noreply@support.sf');
                CaseNotificationmail.setSubject('High budget notification');    
                CaseNotificationmail.setHtmlBody('Please review this high budget position '+ oldPosition.Name);
                mails.add(CaseNotificationmail); 
            }
        }
        insert taskList;    
        Messaging.sendEmail(mails);
    }
}