force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/USA_visa_holder__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_holder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>USA visa holder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_valid_From__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_From__c</fullName>
    <label>USA visa valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_valid_To__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_To__c</fullName>
    <label>USA visa valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/triggers/CandidateVisaHolder/CandidateVisaHolderHelper.cls
public with sharing class CandidateVisaHolderHelper {
    public static void showError(List<Candidate__c> Candidates)
    {
        for(Candidate__c candidateitem: Candidates)
        {
            if(candidateitem.USA_visa_holder__c==true && (	candidateitem.USA_visa_valid_From__c==null || 	candidateitem.USA_visa_valid_To__c==null))
            {
                candidateitem.addError('Please specify your visa date information');
            }
        }  
    }
}