force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_holder__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_holder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>USA visa holder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_valid_From__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_From__c</fullName>
    <label>USA visa valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_valid_To__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_To__c</fullName>
    <label>USA visa valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Years_in_IT__c.field-meta.xml
<CustomField>
    <fullName>Years_in_IT__c</fullName>
    <label>Years in IT</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <description>The salary I would like to have</description>
    <label>Expected Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/JobPosition__c.field-meta.xml
<CustomField>
    <fullName>JobPosition__c</fullName>
    <label>Job Position</label>
    <referenceTo>JobPosition__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobPosition__c/JobPosition__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobPosition__c/fields/CandidateLevel__c.field-meta.xml
<CustomField>
    <fullName>CandidateLevel__c</fullName>
    <label>Candidate Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior Software Engineer</fullName>
            </value>
            <value>
                <fullName>Middle Software Engineer</fullName>
            </value>
            <value>
                <fullName>Senior Software Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Software Engineer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobPosition__c/fields/HR_Manager__c.field-meta.xml
<CustomField>
    <fullName>HR_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>HR Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobPosition__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ukraine</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobPosition__c/fields/Position_Budget__c.field-meta.xml
<CustomField>
    <fullName>Position_Budget__c</fullName>
    <label>Position Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobPosition__c/fields/Practice_Unit__c.field-meta.xml
<CustomField>
    <fullName>Practice_Unit__c</fullName>
    <label>Practice Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobPosition__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/trigger_test/JobApplicationTriggerTest.cls
@isTest
public with sharing class JobApplicationTriggerTest {
    @isTest
    static void  testVisa(){    
        List<JobApplication__c> JobApplications = new List<JobApplication__c>();
        List<JobPosition__c> JobPositions = new List<JobPosition__c>();
        List<Candidate__c> Candidates = new List<Candidate__c>();
        
        Contact contact=new Contact(LastName ='Klery', MailingCountry='USA');    
        insert contact;
        
        for (Integer i = 0; i < 250; ++i) {
            JobPositions.add(new JobPosition__c(Name = 'position'+i,CandidateLevel__c='Junior Software Engineer',Location__c= 'USA' ,Practice_Unit__c='Salesforce',Priority__c='Low',Position_Budget__c=400+i, HR_Manager__c =contact.Id));
            Candidates.add(new Candidate__c(Name = 'candidate'+i,Email__c='fortegroup@gmail.com',PhoneNumber__c='380504159832',Years_in_IT__c=1,USA_visa_holder__c=true,USA_visa_valid_From__c=Date.today()-i,USA_visa_valid_To__c=Date.today().addYears(1)+i) ) ;
            JobApplications.add(new JobApplication__c(Expected_Salary__c=300+i, JobPosition__c=JobPositions[i].Id,Candidate__c=Candidates[i].Id));
        }
        insert JobPositions;
        insert Candidates;
        
        Test.startTest();
        Database.SaveResult[] results = Database.insert(JobApplications, false);
        Test.stopTest();
        
        
        Map <Id,JobPosition__c> positionsMap = new Map  <Id,JobPosition__c> ([Select Id,Location__c from JobPosition__c ]);
        Map <Id,Candidate__c> candidatesMap = new  Map <Id,Candidate__c> ([Select Id,USA_visa_holder__c,USA_visa_valid_From__c,USA_visa_valid_To__c from Candidate__c ]);
        
        Integer k=0;
        for( JobApplication__c  applicationitem: JobApplications)
        {
            JobPosition__c position = positionsMap.get(applicationitem.JobPosition__c);
            Candidate__c candidate= candidatesMap.get(applicationitem.Candidate__c);
            if(position.Location__c == 'USA' && (candidate.USA_visa_holder__c==false || candidate.USA_visa_valid_From__c>Date.Today() || candidate.USA_visa_valid_To__c<Date.Today().addYears(1)))
            {                  
                System.assert(!results[k].isSuccess());
                System.assert(results[k].getErrors().size() > 0);
                System.assertEquals('You can not apply for this job due to your US visa expiration date.', results[k].getErrors()[0].getMessage());
            }
            k++;
        }
    }
}