force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/USA_visa_holder__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_holder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>USA visa holder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_valid_From__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_From__c</fullName>
    <label>USA visa valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_valid_To__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_To__c</fullName>
    <label>USA visa valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/JobPosition__c.field-meta.xml
<CustomField>
    <fullName>JobPosition__c</fullName>
    <label>Job Position</label>
    <referenceTo>JobPosition__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobPosition__c/JobPosition__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobPosition__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ukraine</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/triggers/JobApplicationVisa/JobApplicationVisaHelper.cls
public with sharing class JobApplicationVisaHelper {
    public static void checkVisaDate(List<JobApplication__c> JobApplications){
        for( JobApplication__c  applicationitem: JobApplications)
        {
            if(!(applicationitem.JobPosition__r.Location__c == 'USA' && applicationitem.Candidate__r.USA_visa_holder__c==true && applicationitem.Candidate__r.USA_visa_valid_From__c<=Date.Today() && applicationitem.Candidate__r.USA_visa_valid_To__c>=Date.Today().addYears(1)))
            {
              applicationitem.addError('You can not apply for this job due to your US visa expiration date. ');
            }
        }
    }
}