force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Recovered__c.field-meta.xml
<CustomField>
    <fullName>Recovered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recovered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_holder__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_holder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>USA visa holder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_valid_From__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_From__c</fullName>
    <label>USA visa valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/USA_visa_valid_To__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_To__c</fullName>
    <label>USA visa valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/trigger_test/CandidateTriggerTest.cls
@isTest
public with sharing class CandidateTriggerTest {    
    @isTest
    static void testInsertCandidateWhichVisaHolderTrue()
    {
        List<Candidate__c> Candidates = DataFactory.generateCandidateRecordsInvalid(250);
        List<Candidate__c> CandidatesInvalid = DataFactory.generateCandidateRecordsInvalid(250);
        Candidates.addAll(CandidatesInvalid);
        
        Test.startTest();
        Database.SaveResult[] results = Database.insert(Candidates, false);
        Test.stopTest();
        
        Integer k=0;
        for(Candidate__c candidate:Candidates)
        {
            if(candidate.USA_visa_holder__c==true && (	candidate.USA_visa_valid_From__c==null || 	candidate.USA_visa_valid_To__c==null))
            {
                System.assert(!results[k].isSuccess());
                System.assert(results[k].getErrors().size() > 0);
                System.assertEquals('Please specify your visa date information', results[k].getErrors()[0].getMessage());
            }
            else if(candidate.USA_visa_holder__c==true && 	candidate.USA_visa_valid_From__c!=null && 	candidate.USA_visa_valid_To__c!=null)
            {
                System.assert(results[k].isSuccess());
            }
            k++;
        }
    }
    
    @isTest
    static void testUpdateCandidateWhichVisaHolderTrue()
    {
        List<Candidate__c> Candidates = DataFactory.generateCandidateRecordsInvalid(250);
        List<Candidate__c> CandidatesInvalid = DataFactory.generateCandidateRecordsInvalid(250);
        Candidates.addAll(CandidatesInvalid);
        insert Candidates;
        
        Test.startTest();
        Database.SaveResult[] results = Database.update(Candidates, false);
        Test.stopTest();
        
        Integer k=0;
        for(Candidate__c candidate:Candidates)
        {
            if(candidate.USA_visa_holder__c==true && (	candidate.USA_visa_valid_From__c==null || 	candidate.USA_visa_valid_To__c==null))
            {
                System.assert(!results[k].isSuccess());
                System.assert(results[k].getErrors().size() > 0);
                System.assertEquals('Please specify your visa date information', results[k].getErrors()[0].getMessage());
            }
            else if(candidate.USA_visa_holder__c==true && 	candidate.USA_visa_valid_From__c!=null && 	candidate.USA_visa_valid_To__c!=null)
            {
                System.assert(results[k].isSuccess());
            }            
            k++;
        }
    }
    
    @isTest
    static void testCheckRecoveredAfterUndelete()
    {
        List<Candidate__c> Candidates = DataFactory.generateCandidateRecordsValid(250);
        insert Candidates;
        delete Candidates;
        undelete Candidates;
        
        Candidates = [SELECT Id, Recovered__c FROM Candidate__c];
        
        for(Candidate__c candidate:Candidates) {
            System.assert(candidate.Recovered__c==true);
        }
    }    
}