force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <description>The salary I would like to have</description>
    <label>Expected Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/HR_phone_number__c.field-meta.xml
<CustomField>
    <fullName>HR_phone_number__c</fullName>
    <formula>JobPosition__r.HR_Manager__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HR phone number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/JobPosition__c.field-meta.xml
<CustomField>
    <fullName>JobPosition__c</fullName>
    <label>Job Position</label>
    <referenceTo>JobPosition__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobPosition__c/JobPosition__c.object-meta.xml
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobPosition__c/fields/Open_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Due_Date__c</fullName>
    <label>Open Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ApplicationController.cls
public with sharing class ApplicationController {
    @AuraEnabled(cacheable=true)
    public static List<JobApplication__c> getApplicationList() {
        return [
            SELECT Name, JobPosition__c, Expected_Salary__c, HR_phone_number__c
            FROM JobApplication__c 
            WHERE JobPosition__r.Open_Due_Date__c>TODAY 
            // WITH SECURITY_ENFORCED
            ORDER BY JobPosition__c,Expected_Salary__c
        ];
    }

    @AuraEnabled
    public static JobApplication__c createApplication(JobApplication__c application) {
        system.debug('application==>'+application);
        insert application;
        return application;
    }

    @AuraEnabled(cacheable=false)
    public static void deleteApplications(List<Id> lstApplicationIds){
        List<JobApplication__c> lstToDelete = new List<JobApplication__c>();

        try {
            for(Id idApplication : lstApplicationIds) {
                lstToDelete.add(new JobApplication__c(Id = idApplication));
            }
            if(!lstToDelete.isEmpty()) {
                delete lstToDelete;
            }
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}